python main.py -b google/vit-base-patch16-224 --seed 43
python main.py -b google/vit-base-patch16-224 --seed 44
python main.py -b google/vit-base-patch16-224 --seed 45
python main.py -b openai/clip-vit-base-patch16 --seed 43
python main.py -b openai/clip-vit-base-patch16 --seed 44
python main.py -b openai/clip-vit-base-patch16 --seed 45
python main.py -b vc1 --seed 43
python main.py -b vc1 --seed 44
python main.py -b vc1 --seed 45
python main.py -b resnet50 --seed 43
python main.py -b resnet50 --seed 44
python main.py -b resnet50 --seed 45
python main_SABLAS.py -b google/vit-base-patch16-224 --seed 43
python main_SABLAS.py -b google/vit-base-patch16-224 --seed 44
python main_SABLAS.py -b google/vit-base-patch16-224 --seed 45
python main_SABLAS.py -b openai/clip-vit-base-patch16 --seed 43
python main_SABLAS.py -b openai/clip-vit-base-patch16 --seed 44
python main_SABLAS.py -b openai/clip-vit-base-patch16 --seed 45
python main_SABLAS.py -b vc1 --seed 43
python main_SABLAS.py -b vc1 --seed 44
python main_SABLAS.py -b vc1 --seed 45
python main_SABLAS.py -b resnet50 --seed 43
python main_SABLAS.py -b resnet50 --seed 44
python main_SABLAS.py -b resnet50 --seed 45